// lib/yard-data.ts

export type YardType = 'full_service' | 'saas';
export type YardCategory = 'full_service' | 'west_coast' | 'texas' | 'midwest' | 'southeast' | 'east_coast' | 'florida' | 'national';

export interface Yard {
  id: string;
  name: string;
  commonName: string;
  address: string;
  city: string;
  state: string;
  zip?: string;
  type: YardType;
  category: YardCategory;
  contactPhone?: string;
  contactEmail?: string;
  yardLink?: string;
  aircallNumber?: string;
  features: string[];
  notes?: string;
  accessInstructions?: string;
  automated?: boolean;
}

export const YARDS: Yard[] = [
  // ==================== FULL SERVICE YARDS ====================
  {
    id: 'fs-jax-ellis',
    name: '278 Ellis Road',
    commonName: 'Parking Kingdom Jacksonville - Ellis',
    address: '278 Ellis Rd N',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32254',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '904-265-9233',
    yardLink: 'https://www.theright.com/details/278-ellis-road?duration=monthly',
    aircallNumber: '904-265-9233',
    features: ['Soporte directo', 'Gestión humana', 'Tradicional'],
    notes: 'Also known as Bulls Bay Storage'
  },
  {
    id: 'fs-jax-chase',
    name: '120 Chase Street',
    commonName: 'Parking Kingdom Jacksonville - Chase',
    address: '120 Chase St',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32254',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '904-265-9233',
    yardLink: 'https://www.therightu.com/details/120-chase-street?duration=monthly',
    aircallNumber: '904-265-9233',
    features: ['Ideal para pequeñas flotas', 'Soporte humano directo'],
    notes: 'Small fleets preferred'
  },
  {
    id: 'fs-davie-griffin',
    name: 'Griffin Truck Parking',
    commonName: 'Griffin Truck Parking - Davie',
    address: '5081 SW 48th St',
    city: 'Davie',
    state: 'FL',
    zip: '33314',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '786-471-6281',
    yardLink: 'https://www.therightu.com/details/griffin-truck-parking?duration=monthly',
    aircallNumber: '786-471-6281',
    features: ['Full service', 'Gestión tradicional'],
    notes: 'No website - use provided links'
  },
  {
    id: 'fs-dania-port',
    name: 'Port Everglades Truck Parking',
    commonName: 'Port Everglades - Dania',
    address: '775 Taylor Ln',
    city: 'Dania Beach',
    state: 'FL',
    zip: '33004',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '954-833-6297',
    yardLink: 'https://www.therightu.com/details/port-everglades-truck-parking?duration=monthly',
    aircallNumber: '954-833-6297',
    features: ['Cerca del puerto', 'Full service'],
    notes: 'Managed by Griffin team'
  },
  {
    id: 'fs-davie-burris',
    name: 'Burris Road Truck Parking',
    commonName: 'Burris - Davie',
    address: '3600 Burris Rd',
    city: 'Davie',
    state: 'FL',
    zip: '33314',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '786-471-6281',
    yardLink: 'https://www.therighut.com/details/burris-road-truck-parking?duration=monthly',
    features: ['Full service', 'Usualmente lleno'],
    notes: 'Usually 100% full with long-term tenants'
  },
  {
    id: 'fs-riviera-mrparker',
    name: '3571 Avenue E',
    commonName: 'Mr. Parker USA - Riviera Beach',
    address: '3571 Avenue East',
    city: 'Riviera Beach',
    state: 'FL',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '561-556-8710',
    contactEmail: 'parking@mrparkerusa.com',
    yardLink: 'https://www.therighut.com/details/3571-avenue-e-e-22duration=monthly',
    aircallNumber: '561-489-7958',
    features: ['Full service', 'Mr. Parker network'],
    notes: 'Website: www.mrparkerusa.com'
  },
  {
    id: 'fs-hollywood-mrparker',
    name: '1724 Buchanan Street',
    commonName: 'Mr. Parker USA - Hollywood',
    address: '1724 Buchanan Street',
    city: 'Hollywood',
    state: 'FL',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '561-489-7958',
    contactEmail: 'parking@mrparkerusa.com',
    yardLink: 'https://www.therightt.com/details/1724-buchanan-street?duration=monthly',
    aircallNumber: '561-556-8710',
    features: ['Full service', 'Mr. Parker network'],
    notes: 'Also known as Palm Beach, Hollywood location'
  },
  {
    id: 'fs-georgia-i85',
    name: '212 Allen Road',
    commonName: 'I-85 Truck Parking - Commerce',
    address: '212 Allen Rd',
    city: 'Commerce',
    state: 'GA',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '762-227-5486',
    yardLink: 'https://www.therightt.com/details/212-allen-road?duration=monthly',
    aircallNumber: '762-227-5486',
    features: ['Full service', 'Ubicación estratégica I-85'],
    notes: 'Georgia location'
  },
  {
    id: 'fs-alabama-gulf',
    name: 'Gulf Coast Truck Storage',
    commonName: 'Gulf Coast - Mobile',
    address: '2223 Halls Mill Rd',
    city: 'Mobile',
    state: 'AL',
    zip: '36606',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '251-283-5404',
    yardLink: 'https://www.therightt.com/details/gulf-coast-truck-storage-22duration=monthly',
    aircallNumber: '251-283-5404',
    features: ['Full service', 'Costa del Golfo'],
    notes: 'Mobile, Alabama location'
  },
  {
    id: 'fs-tennessee-national',
    name: 'National Truck Parking - Getwell Road',
    commonName: 'Getwell - Memphis',
    address: '4867 Getwell Road',
    city: 'Memphis',
    state: 'TN',
    type: 'full_service',
    category: 'full_service',
    contactPhone: '901-350-6669',
    yardLink: 'https://www.therighut.com/details/national-truck-parking-getwell-road?duration=monthly',
    aircallNumber: '901-350-6669',
    features: ['Full service', 'Promoción primer mes gratis'],
    notes: 'Promotion: First month free, security deposit required'
  },
  {
    id: 'fs-sc-charleston',
    name: 'Charleston Truck Parking',
    commonName: 'Charleston Truck Parking',
    address: '2398 S Aviation Ave',
    city: 'North Charleston',
    state: 'SC',
    zip: '29406',
    type: 'full_service',
    category: 'full_service',
    aircallNumber: '843-459-7235',
    features: ['Full service', 'Ubicación estratégica'],
    notes: 'Charleston, South Carolina'
  },

  // ==================== SAAS YARDS - WEST COAST ====================
  {
    id: 'saas-or-portland',
    name: '8101 NE 14th Place',
    commonName: 'Industrial Portland - The Truck Depot',
    address: '8101 Northeast 14th Place',
    city: 'Portland',
    state: 'OR',
    zip: '97211',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '360-784-0011',
    contactEmail: 'brice.callison@gmail.com',
    yardLink: 'https://www.theright.com/details/8101-ne-14th-place?duration=monthly',
    features: ['Smart Gate', 'SAAS', 'Reservas online'],
    accessInstructions: 'Smart Gate',
    automated: true
  },
  {
    id: 'saas-id-falls',
    name: 'Truckers Landing',
    commonName: 'Truckers Landing',
    address: '4542 N 25th E',
    city: 'Idaho Falls',
    state: 'ID',
    zip: '83401',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '208-680-9902',
    yardLink: 'https://www.therighut.com/details/truckers-la nding?duration=mont hly',
    features: ['Gate access', 'SAAS', 'Automatizado'],
    accessInstructions: 'Gate',
    automated: true
  },
  {
    id: 'saas-ca-stockton-navy',
    name: '1111 Navy Drive',
    commonName: 'Powerlane Logistics - Navy Drive',
    address: '1111 Navy Drive',
    city: 'Stockton',
    state: 'CA',
    zip: '95206',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '209-203-4186',
    yardLink: 'https://www.therighut.com/details/TTI-navy-d rive?duration=monthly',
    features: ['Gate access', 'SAAS', 'Stockton yard'],
    accessInstructions: 'Gate',
    automated: true
  },
  {
    id: 'saas-ca-stockton-broadway',
    name: '1011 N Broadway',
    commonName: 'Fswc - Stockton Yard',
    address: '1011 N Broadway Ave',
    city: 'Stockton',
    state: 'CA',
    zip: '95205',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '209-993-3737',
    yardLink: 'https://www.therighut.com/details/10Ti-n-broadway?duration=month ly',
    features: ['Gate access', 'SAAS'],
    automated: true
  },
  {
    id: 'saas-ca-wilmington',
    name: '222 Quay Avenue',
    commonName: 'Truckspace - Wilmington',
    address: '222 Quay Avenue',
    city: 'Wilmington',
    state: 'CA',
    zip: '90744',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '201-323-6323',
    yardLink: 'https://www.therighut.com/details/222-quay-avenue?duration=monthly',
    features: ['SAAS', 'Automatizado'],
    automated: true
  },
  {
    id: 'saas-ca-compton',
    name: '2201 Santa Fe',
    commonName: 'Truckspace/Rickey Powell - Compton',
    address: '2201 South Santa Fe Avenue',
    city: 'Compton',
    state: 'CA',
    zip: '90221',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '570-760-9031',
    yardLink: 'https://www.therighut.com/details/2201-santa -fe?duration=monthly',
    features: ['SAAS', 'Los Angeles area'],
    automated: true
  },
  {
    id: 'saas-ca-highland',
    name: 'Highland',
    commonName: 'Sugar Creek Enterprises - Highland',
    address: '27356 5th Street',
    city: 'Highland',
    state: 'CA',
    zip: '92346',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '951-377-0268',
    contactEmail: 'rent@scetrans.com',
    yardLink: 'https://www.therighut.com/details/highland? duration=monthly',
    features: ['SAAS', 'Inland Empire'],
    automated: true
  },
  {
    id: 'saas-ca-adelanto',
    name: '12450 Hibiscus Rd',
    commonName: 'United Storage Yard',
    address: '12450 Hibiscus Rd',
    city: 'Adelanto',
    state: 'CA',
    zip: '92301',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '760-493-2188',
    contactEmail: 'unitedstorageyard@gmail.com',
    yardLink: 'https://www.therighut.com/details/12450-hibi.scus-rd?duration=monthly',
    features: ['SAAS', 'High Desert location'],
    automated: true
  },
  {
    id: 'saas-ca-sandiego',
    name: 'Otay Mesa - Sonet Truck & Trailer Parking Facility',
    commonName: 'San Diego - Otay Mesa',
    address: '9060 Siempre Viva Rd',
    city: 'San Diego',
    state: 'CA',
    zip: '92154',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '619-623-0863',
    contactEmail: 'gerardoc@sonettransportation.com',
    yardLink: 'https://www.therighut.com/details/otay-mesa-sonet-truck-trailer-parking-facility?duration=monthly',
    features: ['SAAS', 'Border location', 'Truck & Trailer'],
    automated: true
  },
  {
    id: 'saas-ca-ranchocucamonga',
    name: 'Real Term Rancho',
    commonName: 'Rancho Cucamonga',
    address: '8566 Pecan Ave',
    city: 'Rancho Cucamonga',
    state: 'CA',
    zip: '91739',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '840-237-4440',
    contactEmail: '8566pecan@truckspace.co',
    yardLink: 'https://www.therigh ut.com/details/real-term-rancho-cucamon ga?duration=monthly',
    features: ['SAAS', 'Inland Empire'],
    automated: true
  },
  {
    id: 'saas-ca-elkgrove',
    name: '10144 Waterman Road',
    commonName: 'Elk Grove',
    address: '10144 Waterman Road',
    city: 'Elk Grove',
    state: 'CA',
    zip: '95624',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '916-207-2580',
    contactEmail: 'mouharenterprise@yahoo.com',
    yardLink: 'https://www.therighut.com/details/10144-waterman-road?duration=monthly',
    features: ['SAAS', 'Sacramento area'],
    automated: true
  },

  // ==================== SAAS YARDS - TEXAS ====================
  {
    id: 'saas-tx-fortworth-markum',
    name: '1400 Markum Ranch Road East',
    commonName: 'RCR Rail - Fort Worth',
    address: '1400 Markum Ranch Rd E',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76126',
    type: 'saas',
    category: 'texas',
    contactPhone: '570-760-9031',
    contactEmail: 'retail@truckspace.co',
    yardLink: 'https://www.therighut.com/details/1400-markum-ranch-road-east?duration=monthly',
    features: ['SAAS', 'DFW area'],
    automated: true
  },
  {
    id: 'saas-tx-fortworth-jowell',
    name: 'Jowell Business Park',
    commonName: 'Birddog Ventures - Jowell',
    address: '2591 NE 28th St',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76111',
    type: 'saas',
    category: 'texas',
    contactPhone: '214-546-6135',
    contactEmail: 'jd@b6vtx.com',
    yardLink: 'https://www.therighut.com/details/jowell-business-park?duration=monthly',
    features: ['SAAS', 'Business park'],
    automated: true
  },
  {
    id: 'saas-tx-haltom',
    name: '3900 N Beach St',
    commonName: 'FF Real Estate - Haltom City',
    address: '3900 N Beach St',
    city: 'Haltom City',
    state: 'TX',
    zip: '76137',
    type: 'saas',
    category: 'texas',
    contactPhone: '469-669-0971',
    contactEmail: 'ron@ffrealesgate.net',
    yardLink: 'https://www.therighut.com/details/3900-n-beach-st?duration=monthly',
    features: ['SAAS', 'DFW metroplex'],
    automated: true
  },
  {
    id: 'saas-tx-fortworth-freeway',
    name: '7700 South Freeway',
    commonName: 'Powerlane Logistics - Fort Worth',
    address: '7700 South Fwy',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76134',
    type: 'saas',
    category: 'texas',
    contactPhone: '209-203-4186',
    contactEmail: 'Nilton@powerlanelogistics.com',
    yardLink: 'https://www.therighut.com/details/7700-south-freeway?duration=monthly',
    features: ['Gate access', 'SAAS', 'Freeway location'],
    accessInstructions: 'Gate',
    automated: true
  },
  {
    id: 'saas-tx-fortworth-carey',
    name: '4902 Carey St',
    commonName: 'FF Real Estate - Fort Worth',
    address: '4902 Carey St',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76119',
    type: 'saas',
    category: 'texas',
    contactPhone: '469-669-0971',
    contactEmail: 'ron@ffrealesgate.net',
    yardLink: 'https://www.therighut.com/details/4902-carey-st?duration=monthly',
    features: ['SAAS', 'Fort Worth'],
    automated: true
  },
  {
    id: 'saas-tx-grandprairie',
    name: '500 W Oakdale Road',
    commonName: 'USA Storage Yards - Oakdale',
    address: '500 W Oakdale Rd',
    city: 'Grand Prairie',
    state: 'TX',
    zip: '75050',
    type: 'saas',
    category: 'texas',
    contactPhone: '937-901-1742',
    contactEmail: 'andrea@usastorageyard.s.com',
    yardLink: 'https://www.therighut.com/details/500-w-oakdale-road?duration=monthly',
    features: ['SAAS', 'Between Dallas & Fort Worth'],
    automated: true
  },
  {
    id: 'saas-tx-frisco',
    name: 'Frisco: 23000 PR 3411',
    commonName: 'TCC Equipment - Frisco',
    address: '23000 PR 3411',
    city: 'Frisco',
    state: 'TX',
    type: 'saas',
    category: 'texas',
    contactPhone: '903-201-5221',
    yardLink: 'https://www.therighut.com/details/frisco-23000-pr-3411?duration=monthly',
    features: ['SAAS', 'North Dallas area'],
    automated: true
  },
  {
    id: 'saas-tx-littleelm',
    name: 'Doe Branch Industrial Storage & Parking',
    commonName: 'Doe Branch',
    address: '2270 Doe Branch Rd',
    city: 'Little Elm',
    state: 'TX',
    zip: '75068',
    type: 'saas',
    category: 'texas',
    contactPhone: '469-843-0308',
    yardLink: 'https://www.therighut.com/details/doe-branch-industrial-storage-parking?duration=monthly',
    features: ['SAAS', 'Industrial storage'],
    automated: true
  },
  {
    id: 'saas-tx-celina',
    name: 'Celina: FM 428',
    commonName: 'TCC Equipment - Celina',
    address: '428 Private Road 901',
    city: 'Celina',
    state: 'TX',
    type: 'saas',
    category: 'texas',
    contactPhone: '903-201-5221',
    yardLink: 'https://www.therighut.com/details/celina-fm-428?duration=monthly',
    features: ['SAAS', 'North of Dallas'],
    automated: true
  },
  {
    id: 'saas-tx-dallas-crystal',
    name: '5610 Crystal Lake Blvd',
    commonName: 'Crystal Lake',
    address: '5610 Crystal Lake Blvd',
    city: 'Dallas',
    state: 'TX',
    zip: '75236',
    type: 'saas',
    category: 'texas',
    contactPhone: '903-201-5221',
    yardLink: 'https://www.therighut.com/details/5610-crystal-lake-blvd?duration=monthly',
    features: ['SAAS', 'South Dallas'],
    automated: true
  },
  {
    id: 'saas-tx-dallas-bluebird',
    name: '5307 Bluebird Ave',
    commonName: 'Realize Truck Parking - Dallas Bluebird',
    address: '5307 Bluebird Ave',
    city: 'Dallas',
    state: 'TX',
    zip: '75236',
    type: 'saas',
    category: 'texas',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/5307-bluebird-ave?duration=monthly',
    features: ['SAAS', 'Realize network', 'Refund via email'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-tx-dallas-duncanville1',
    name: '3934 Duncanville Road',
    commonName: 'Duncanville - Dallas',
    address: '3934 Duncanville Rd',
    city: 'Dallas',
    state: 'TX',
    zip: '75236',
    type: 'saas',
    category: 'texas',
    contactPhone: '469-404-8573',
    contactEmail: 'parking@ledbetterindus trial.com',
    yardLink: 'https://www.therighut.com/details/3934-dunc-anville-road?duration=monthly',
    features: ['SAAS', 'Duncanville area'],
    automated: true
  },
  {
    id: 'saas-tx-dallas-duncanville2',
    name: '3600 Duncanville Road',
    commonName: 'Duncanville - Dallas',
    address: '3600 Duncanville Rd',
    city: 'Dallas',
    state: 'TX',
    zip: '75236',
    type: 'saas',
    category: 'texas',
    contactPhone: '469-404-8573',
    contactEmail: 'parking@ledbetterindus trial.com',
    yardLink: 'https://www.therighut.com/details/3600-dunc-anville-road?duration=monthly',
    features: ['SAAS', 'Duncanville area'],
    automated: true
  },
  {
    id: 'saas-tx-dallas-riveroaks',
    name: '4403 River Oaks Drive',
    commonName: 'USA Storage Yards - Dallas',
    address: '4403 River Oaks Dr',
    city: 'Dallas',
    state: 'TX',
    zip: '75241',
    type: 'saas',
    category: 'texas',
    contactPhone: '937-901-1742',
    contactEmail: 'andrea@usastorageyard s.com',
    yardLink: 'https://www.therighut.com/details/4403-river-oaks-drive?duration=monthly',
    features: ['SAAS', 'River Oaks area'],
    automated: true
  },
  {
    id: 'saas-tx-hutchins',
    name: '2386 Fulghum Road',
    commonName: 'Realize Truck Parking - Hutchins',
    address: '2386 Fulghum Rd',
    city: 'Hutchins',
    state: 'TX',
    zip: '75141',
    type: 'saas',
    category: 'texas',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/2386-fulghum-road?duration=monthly',
    features: ['SAAS', 'Realize network', 'South Dallas'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-tx-caddomills',
    name: 'Park 87',
    commonName: 'Park 87',
    address: '211 FM1903',
    city: 'Caddo Mills',
    state: 'TX',
    zip: '75135',
    type: 'saas',
    category: 'texas',
    contactPhone: '214-578-8151',
    contactEmail: 'park87tx@gmail.com',
    yardLink: 'https://www.therighut.com/details/park-87?duration=monthly',
    features: ['SAAS', 'East of Dallas'],
    automated: true
  },
  {
    id: 'saas-tx-coupland',
    name: 'Pioneer Truck Parking: 21000 Cameron Road',
    commonName: 'Pioneer Truck Parking',
    address: '21000 Cameron Road',
    city: 'Coupland',
    state: 'TX',
    type: 'saas',
    category: 'texas',
    contactPhone: '844-512-7275',
    contactEmail: 'contact@pioneerparknst ore.com',
    yardLink: 'https://www.therightt. com/details/pioneer-tr uck-parking-21000-ca meron-road?duration= monthly',
    features: ['SAAS', 'East of Austin'],
    automated: true
  },
  {
    id: 'saas-tx-taylor',
    name: 'RCR Taylor Rail Logistics Park',
    commonName: 'RCR Rail - Taylor Rail',
    address: '201 FM3349',
    city: 'Taylor',
    state: 'TX',
    type: 'saas',
    category: 'texas',
    contactPhone: '570-760-9031',
    contactEmail: 'rcrail@truckspace.co',
    yardLink: 'https://www.therightt. com/details/rcr-taylor-rail-logistics-par k?duration=monthly',
    features: ['SAAS', 'Rail logistics park'],
    automated: true
  },
  {
    id: 'saas-tx-hempstead',
    name: 'RCR Hempstead',
    commonName: 'RCR Rail - Hempstead',
    address: '23639 State Highway 6',
    city: 'Hempstead',
    state: 'TX',
    type: 'saas',
    category: 'texas',
    contactPhone: '570-760-9031',
    contactEmail: 'rcrail@truckspace.co',
    yardLink: 'https://www.therightt. com/details/rcr-hempstead?duration= monthly',
    features: ['SAAS', 'West of Houston'],
    automated: true
  },
  {
    id: 'saas-tx-conroe',
    name: 'Truck Harbor',
    commonName: 'Truck Harbor',
    address: '20 Sherbrook Circle',
    city: 'Conroe',
    state: 'TX',
    zip: '77385',
    type: 'saas',
    category: 'texas',
    contactPhone: '512-710-9715',
    contactEmail: 'steelboxselfstorage@gmail.com',
    yardLink: 'https://www.therightt. com/details/truck-harbor?duration=monthly',
    features: ['SAAS', 'North Houston'],
    automated: true
  },
  {
    id: 'saas-tx-dayton',
    name: 'USA Chassis, Storage, and Industrial Solutions',
    commonName: 'USA Chassis',
    address: '322 County Rd 603',
    city: 'Dayton',
    state: 'TX',
    zip: '77535',
    type: 'saas',
    category: 'texas',
    contactPhone: '786-760-5003',
    yardLink: 'https://www.therigh ut.com/details/usa-c hassis-storage-and-i ndustrial-solutions?duration=monthly',
    features: ['SAAS', 'Chassis storage'],
    automated: true
  },
  {
    id: 'saas-tx-houston-williams',
    name: 'Williams Truck Parking - Houston',
    commonName: 'Williams Truck Parking',
    address: '6734 E Mt Houston Rd',
    city: 'Houston',
    state: 'TX',
    zip: '77050',
    type: 'saas',
    category: 'texas',
    contactPhone: '713-550-3026',
    yardLink: 'https://www.therigh ut.com/details/williams-truck-parking-ho uston?duration=monthly',
    features: ['SAAS', 'North Houston'],
    automated: true
  },
  {
    id: 'saas-tx-houston-spanish',
    name: '4402 Old Spanish Trail E Dr',
    commonName: 'Realize Truck Parking - Houston Old Spanish',
    address: '4402 Old Spanish Trail E Dr',
    city: 'Houston',
    state: 'TX',
    zip: '77013',
    type: 'saas',
    category: 'texas',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therigh ut.com/details/4402-old-spanish-trail-e-d r-houston-tx-770137 duration=monthly',
    features: ['SAAS', 'Realize network', 'East Houston'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-tx-houston-wallisville',
    name: '10608 Wallisville Road',
    commonName: 'USA Storage Yards - Wallisville',
    address: '10608 Wallisville Rd',
    city: 'Houston',
    state: 'TX',
    zip: '77013',
    type: 'saas',
    category: 'texas',
    contactPhone: '937-901-1742',
    yardLink: 'https://www.therigh ut.com/details/10608 -wallisville-road?duration=monthly',
    features: ['SAAS', 'East Houston'],
    automated: true
  },
  {
    id: 'saas-tx-fortworth-northstar',
    name: 'North Star Truck Parking',
    commonName: 'North Star Truck Parking Fort Worth',
    address: '3428 Deen Rd',
    city: 'Fort Worth',
    state: 'TX',
    zip: '76106',
    type: 'saas',
    category: 'texas',
    contactPhone: '817-819-2806',
    contactEmail: 'nick@northstarc.com',
    features: ['SAAS', 'No link available'],
    notes: 'No link available',
    automated: true
  },
  {
    id: 'saas-tx-houston-knightrider',
    name: 'KnightRider North Houston',
    commonName: 'KnightRider - Houston',
    address: '17627 Aldine Westfield Road',
    city: 'Houston',
    state: 'TX',
    type: 'saas',
    category: 'texas',
    contactPhone: '713-357-0069',
    contactEmail: 'info@knightriderparking.com',
    yardLink: 'https://www.therigh ut.com/details/knightrider-north-houston ?duration=monthly',
    features: ['SAAS', 'KnightRider network'],
    automated: true
  },
  {
    id: 'saas-tx-pasadena-knightrider',
    name: 'KnightRider Pasadena',
    commonName: 'KnightRider - Pasadena',
    address: '1818 Allen Genoa Rd',
    city: 'Houston',
    state: 'TX',
    zip: '77017',
    type: 'saas',
    category: 'texas',
    contactPhone: '713-357-0069',
    contactEmail: 'info@knightriderparking.com',
    yardLink: 'http://therighut.com/details/knightrider-pasadena?duration=monthly',
    features: ['SAAS', 'KnightRider network', 'Pasadena'],
    automated: true
  },
  {
    id: 'saas-tx-edinburg',
    name: 'I-69 Parking & Storage',
    commonName: 'I-69 - Edinburg',
    address: '8909 N Expressway 281',
    city: 'Edinburg',
    state: 'TX',
    type: 'saas',
    category: 'texas',
    contactPhone: '956-221-0469',
    contactEmail: 'sales@i-69storage.com',
    yardLink: 'https://www.therighut.com/details/i-69-parking-storage?duration=monthly',
    features: ['SAAS', 'South Texas', 'I-69 corridor'],
    automated: true
  },

  // ==================== SAAS YARDS - MIDWEST ====================
  {
    id: 'saas-mn-minneapolis-irving',
    name: 'Irving MSP Lot',
    commonName: 'Nomad - Irving',
    address: '155 Irving Ave N',
    city: 'Minneapolis',
    state: 'MN',
    type: 'saas',
    category: 'midwest',
    contactPhone: '612-255-0377',
    contactEmail: 'mustafs1313@gmail.com',
    yardLink: 'https://www.therighut.com/details/irving-msp -lot?duration=monthly',
    features: ['SAAS', 'Nomad network', 'Minneapolis'],
    automated: true
  },
  {
    id: 'saas-mn-eagan',
    name: 'Nomad Eagan (Dodd Rd)',
    commonName: 'Nomad - Eagan',
    address: '915 Yankee Doodle Rd',
    city: 'Eagan',
    state: 'MN',
    zip: '55121',
    type: 'saas',
    category: 'midwest',
    contactPhone: '612-255-0377',
    contactEmail: 'mustafs1313@gmail.com',
    yardLink: 'https://www.therighut.com/details/nomad-eagan-dodd-rd?duration =monthly',
    features: ['SAAS', 'Nomad network', 'Twin Cities'],
    automated: true
  },
  {
    id: 'saas-mn-minneapolis-fremont',
    name: 'Nomad Minneapolis (Fremont Ave N.)',
    commonName: 'Nomad - Minneapolis',
    address: '250 Fremont Ave N',
    city: 'Minneapolis',
    state: 'MN',
    zip: '55405',
    type: 'saas',
    category: 'midwest',
    contactPhone: '612-255-0377',
    contactEmail: 'mustafs1313@gmail.com',
    yardLink: 'https://www.therighut.com/details/nomad-minneapolis-fremont-ave-n?duration=monthly',
    features: ['SAAS', 'Nomad network', 'Minneapolis'],
    automated: true
  },
  {
    id: 'saas-mo-kansascity',
    name: '1640 Guinotte Ave',
    commonName: 'Sapatsring RE - Guinotte',
    address: '1640 Guinotte Ave',
    city: 'Kansas City',
    state: 'MO',
    zip: '64120',
    type: 'saas',
    category: 'midwest',
    contactPhone: '816-806-6990',
    contactEmail: 'contact@sapatsring.co m',
    yardLink: 'https://www.therighut.com/details/1640-guinotte-ave?duration=monthly',
    features: ['SAAS', 'Kansas City'],
    automated: true
  },
  {
    id: 'saas-il-granitecity',
    name: '1520 East Chain of Rocks Road',
    commonName: 'Granite City',
    address: '1520 Chain of Rocks Rd',
    city: 'Granite City',
    state: 'IL',
    zip: '62040',
    type: 'saas',
    category: 'midwest',
    contactPhone: '314-393-3806',
    yardLink: 'https://www.therigh ut.com/details/1520-east-chain-of-rocks-road?duration=monthly',
    features: ['SAAS', 'St. Louis area'],
    automated: true
  },
  {
    id: 'saas-mo-bridgeton1',
    name: '13816 Missouri Bottom Road',
    commonName: 'Bridgeton',
    address: '13816 Missouri Bottom Rd',
    city: 'Bridgeton',
    state: 'MO',
    zip: '63044',
    type: 'saas',
    category: 'midwest',
    contactPhone: '314-393-3806',
    yardLink: 'https://www.therigh ut.com/details/13816-missouri-bottom-road?duration=monthly',
    features: ['SAAS', 'St. Louis area'],
    automated: true
  },
  {
    id: 'saas-mo-bridgeton2',
    name: '4608 Crossroads Industrial',
    commonName: 'Bridgeton',
    address: '4608 Crossroads Industrial Dr',
    city: 'Bridgeton',
    state: 'MO',
    zip: '63044',
    type: 'saas',
    category: 'midwest',
    contactPhone: '314-393-3806',
    yardLink: 'https://www.therigh ut.com/details/4608-crossroads-industrial ?duration=monthly',
    features: ['SAAS', 'Industrial park'],
    automated: true
  },
  {
    id: 'saas-il-monee',
    name: 'Monee Truck Park and Storage',
    commonName: 'Monee',
    address: '24065 S Cicero Ave',
    city: 'Monee',
    state: 'IL',
    zip: '60449',
    type: 'saas',
    category: 'midwest',
    contactPhone: '312-543-6149',
    yardLink: 'https://www.therigh ut.com/details/monee-truck-park-and-storage?duration=monthly',
    features: ['SAAS', 'Chicago area'],
    automated: true
  },
  {
    id: 'saas-in-gary',
    name: '3870 Chase Street',
    commonName: 'Gary',
    address: '3870 Chase St',
    city: 'Gary',
    state: 'IN',
    zip: '46408',
    type: 'saas',
    category: 'midwest',
    contactPhone: '312-478-1207',
    yardLink: 'https://www.therigh ut.com/details/3870-chase-street?duration=monthly',
    features: ['SAAS', 'Indiana', 'Chicago area'],
    automated: true
  },
  {
    id: 'saas-in-indianapolis1',
    name: '2104 West Epler',
    commonName: 'P and J\'s',
    address: '2104 W Epler Ave',
    city: 'Indianapolis',
    state: 'IN',
    zip: '46217',
    type: 'saas',
    category: 'midwest',
    contactPhone: '317-787-4333',
    yardLink: 'https://www.therigh.ut.com/details/2104-west-epler?duration=monthly',
    features: ['SAAS', 'Indianapolis'],
    automated: true
  },
  {
    id: 'saas-in-indianapolis2',
    name: '2120 West Epler',
    commonName: 'P and J\'s',
    address: '2120 West Epler Avenue',
    city: 'Indianapolis',
    state: 'IN',
    zip: '46217',
    type: 'saas',
    category: 'midwest',
    contactPhone: '317-787-4333',
    yardLink: 'https://www.therigh.ut.com/details/2120-west-epler?duration=monthly',
    features: ['SAAS', 'Indianapolis'],
    automated: true
  },
  {
    id: 'saas-in-indianapolis3',
    name: '1215 West Thompson Ave.',
    commonName: 'P and J\'s',
    address: '1215 Thompson Road',
    city: 'Indianapolis',
    state: 'IN',
    zip: '46217',
    type: 'saas',
    category: 'midwest',
    contactPhone: '317-787-4333',
    yardLink: 'https://www.therigh.ut.com/details/1215-west-thompson-ave?duration=monthly',
    features: ['SAAS', 'Indianapolis'],
    automated: true
  },
  {
    id: 'saas-oh-toledo',
    name: 'Sam\'s Hub - Truck & Trailer Parking',
    commonName: 'Sam\'s Hubs',
    address: '4775 Kettering Dr',
    city: 'Toledo',
    state: 'OH',
    zip: '43612',
    type: 'saas',
    category: 'midwest',
    contactPhone: '419-283-6387',
    yardLink: 'https://www.therigh.ut.com/details/samshub-truck-trailer-parking?duration=monthly',
    features: ['SAAS', 'Toledo', 'Truck & Trailer'],
    automated: true
  },
  {
    id: 'saas-il-joliet',
    name: '1110 Manhattan Rd',
    commonName: 'Zee Le Joliet',
    address: '1110 Manhattan Road',
    city: 'Joliet',
    state: 'IL',
    type: 'saas',
    category: 'midwest',
    contactPhone: '630-398-2585',
    contactEmail: 'zeeleellc@gmail.com',
    yardLink: 'https://www.therighut.com/details/1110-manhattan-rd?duration=monthly',
    features: ['SAAS', 'Chicago area'],
    automated: true
  },

  // ==================== SAAS YARDS - SOUTHEAST ====================
  {
    id: 'saas-tn-memphis-mclemore',
    name: '109 W McLemore Ave',
    commonName: 'Realize Truck Parking - Memphis',
    address: '109 W McLemore Ave',
    city: 'Memphis',
    state: 'TN',
    zip: '38106',
    type: 'saas',
    category: 'southeast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/109-w-mclemore-ave?duration=monthly',
    features: ['SAAS', 'Realize network', 'Memphis'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-tn-lavergne-waldron',
    name: '381 Waldron Road',
    commonName: 'Realize Truck Parking - La Vergne',
    address: '381 Waldron Rd',
    city: 'La Vergne',
    state: 'TN',
    zip: '37086',
    type: 'saas',
    category: 'southeast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/381-waldron-road?duration=monthly',
    features: ['SAAS', 'Realize network', 'Nashville area'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-tn-lavergne-hennessy1',
    name: '1730 JP Hennessy',
    commonName: 'Realize Truck Parking - La Vergne',
    address: '1730 J P Hennessy Dr',
    city: 'La Vergne',
    state: 'TN',
    zip: '37086',
    type: 'saas',
    category: 'southeast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/1730-jp-hennessy',
    features: ['SAAS', 'Realize network', 'Nashville area'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-tn-lavergne-hennessy2',
    name: '1701 JP Hennessy',
    commonName: 'Realize Truck Parking - La Vergne',
    address: '1701 J P Hennessy Dr',
    city: 'La Vergne',
    state: 'TN',
    zip: '37086',
    type: 'saas',
    category: 'southeast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/1701-jp-hennessy?duration=monthly',
    features: ['SAAS', 'Realize network', 'Nashville area'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-ga-dallas-hwy61',
    name: 'Highway 61 Parking',
    commonName: 'Affordable Parking - Highway 61',
    address: '2394 Villa Rica Hwy',
    city: 'Dallas',
    state: 'GA',
    zip: '30157',
    type: 'saas',
    category: 'southeast',
    contactPhone: '404-922-7716',
    contactEmail: 'affordableparking2llc@qmall.com',
    yardLink: 'https://www.therigh ut.com/details/high way-61-parking?duration=monthly',
    features: ['SAAS', 'Affordable Parking network'],
    notes: 'All updates/cancellations through landlord',
    automated: true
  },
  {
    id: 'saas-ga-hiram-hwy92',
    name: 'Highway 92',
    commonName: 'Affordable Parking - Highway 92',
    address: '282 Hiram Acworth Hwy',
    city: 'Hiram',
    state: 'GA',
    zip: '30141',
    type: 'saas',
    category: 'southeast',
    contactPhone: '404-922-7716',
    contactEmail: 'affordableparking2llc@qmall.com',
    yardLink: 'https://www.therigh ut.com/details/high way-92-parking?duration=monthly',
    features: ['SAAS', 'Affordable Parking network'],
    notes: 'All updates/cancellations through landlord',
    automated: true
  },
  {
    id: 'saas-ga-hiram-old92',
    name: 'Old 92',
    commonName: 'Affordable Parking - Old 92',
    address: '1434 Hiram Douglasville Highway',
    city: 'Hiram',
    state: 'GA',
    type: 'saas',
    category: 'southeast',
    contactPhone: '404-922-7716',
    contactEmail: 'affordableparking2llc@qmall.com',
    yardLink: 'https://www.therigh ut.com/details/old-92?duration=monthly',
    features: ['SAAS', 'Affordable Parking network'],
    notes: 'All updates/cancellations through landlord',
    automated: true
  },
  {
    id: 'saas-ga-hiram-tractor',
    name: 'Tractor Trailer Parking LLC',
    commonName: 'Affordable Parking - Tractor Trailer',
    address: '297 Reynolds Road',
    city: 'Hiram',
    state: 'GA',
    type: 'saas',
    category: 'southeast',
    contactPhone: '404-922-7716',
    contactEmail: 'affordableparking2llc@qmall.com',
    yardLink: 'https://www.therighut.com/details/tractor-trailer-parking-llc?duration=monthly',
    features: ['SAAS', 'Affordable Parking network'],
    notes: 'All updates/cancellations through landlord',
    automated: true
  },
  {
    id: 'saas-ga-forestpark',
    name: '5166 John G Glover Ind.',
    commonName: 'Realize Truck Parking - Forest Park',
    address: '5166 John G Glover Ind Ct',
    city: 'Forest Park',
    state: 'GA',
    zip: '30297',
    type: 'saas',
    category: 'southeast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/5166-john-g-glover-ind?duration=monthly',
    features: ['SAAS', 'Realize network', 'Atlanta area'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-ga-lithonia',
    name: 'Nelson Truck Parking - Lithonia',
    commonName: 'Nelson Trucking Parking - Lithonia',
    address: '6759 Marbut Rd',
    city: 'Lithonia',
    state: 'GA',
    zip: '30058',
    type: 'saas',
    category: 'southeast',
    contactPhone: '678-480-1063',
    contactEmail: 'schubertwilliam@gmail.com',
    yardLink: 'https://www.therighut.com/details/helson-truck-parking-lithonia?duration=monthly',
    features: ['SAAS', 'Atlanta area'],
    automated: true
  },
  {
    id: 'saas-ga-loganville-hwy78',
    name: 'HWY 78',
    commonName: 'Realize Truck Parking - Loganville',
    address: '2970 U.S. 78',
    city: 'Loganville',
    state: 'GA',
    type: 'saas',
    category: 'southeast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/hwy-7 82duration=monthly',
    features: ['SAAS', 'Realize network', 'Atlanta area'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-ga-loganville-lowry',
    name: '2720 Lowry',
    commonName: 'Realize Truck Parking - Loganville',
    address: '2720 Lowry Rd',
    city: 'Loganville',
    state: 'GA',
    zip: '30052',
    type: 'saas',
    category: 'southeast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therigh ut.com/details/2720-1 owry?duration=mon thly',
    features: ['SAAS', 'Realize network', 'Atlanta area'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-ga-augusta',
    name: 'Big Sky Truck Parking',
    commonName: 'Lumpkin Rd - Augusta',
    address: '2878 Lumpkin Rd',
    city: 'Augusta',
    state: 'GA',
    zip: '30906',
    type: 'saas',
    category: 'southeast',
    contactPhone: '704-389-0864',
    yardLink: 'https://www.therigh ut.com/details/big-sk y-truck-parking?dur ation=monthly',
    features: ['SAAS', 'Augusta GA'],
    automated: true
  },
  {
    id: 'saas-ga-calhoun-superior',
    name: 'Superior Truck Parking',
    commonName: 'Superior - Calhoun',
    address: '501 Richardson Rd SE',
    city: 'Calhoun',
    state: 'GA',
    type: 'saas',
    category: 'southeast',
    contactPhone: '678-520-4533',
    contactEmail: 'dgysin@bellsouth.net',
    yardLink: 'https://www.therigh ut.com/details/superior-truck-parking?duration=monthly',
    features: ['SAAS', 'North Georgia'],
    automated: true
  },

  // ==================== SAAS YARDS - EAST COAST ====================
  {
    id: 'saas-ny-florida',
    name: '4428 New York 94',
    commonName: 'Realize Truck Parking - New York',
    address: '4428 NY-94',
    city: 'Florida',
    state: 'NY',
    zip: '10921',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therigh ut.com/details/4428-new-york-94?duration=monthly',
    features: ['SAAS', 'Realize network', 'New York'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-ny-statenisland',
    name: '135 Englewood',
    commonName: 'Englewood - Staten Island',
    address: '135 Englewood Ave',
    city: 'Staten Island',
    state: 'NY',
    zip: '10309',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '201-323-6323',
    yardLink: 'https://www.therigh ut.com/details/135-e nglewood?duration= monthly',
    features: ['SAAS', 'New York City area'],
    automated: true
  },
  {
    id: 'saas-pa-croydon',
    name: 'Bensalem Travel Plaza',
    commonName: 'Ossco Group - Croydon',
    address: '2307 Bristol Pike',
    city: 'Croydon',
    state: 'PA',
    zip: '19021',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '215-783-0477',
    yardLink: 'https://www.therigh ut.com/details/bensa lem-travel-plaza?duration=monthly',
    features: ['SAAS', 'Travel plaza', 'Pennsylvania'],
    automated: true
  },
  {
    id: 'saas-pa-bensalem1',
    name: '2950 Secure Drop Lot',
    commonName: 'Philadelphia I-95 Truck Park - Bensalem',
    address: '2950 State Rd.',
    city: 'Bensalem',
    state: 'PA',
    zip: '19020',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '215-237-2436',
    yardLink: 'https://www.therigh ut.com/details/2950-secure-drop-lot?duration=monthly',
    features: ['SAAS', 'I-95 corridor'],
    automated: true
  },
  {
    id: 'saas-pa-bensalem2',
    name: '2500 SRH',
    commonName: 'Philadelphia I-95 Truck Park - Bensalem',
    address: '2522 State Road',
    city: 'Bensalem',
    state: 'PA',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '215-237-2436',
    yardLink: 'https://www.therigh ut.com/details/2500-srh?duration=monthly',
    features: ['SAAS', 'I-95 corridor'],
    automated: true
  },
  {
    id: 'saas-pa-bensalem3',
    name: '2700 Lot G',
    commonName: 'Philadelphia I-95 Truck Park - Bensalem',
    address: '2700 State Rd.',
    city: 'Bensalem',
    state: 'PA',
    zip: '19020',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '215-237-2436',
    yardLink: 'https://www.therigh ut.com/details/2700-l ot-g?duration=monthly',
    features: ['SAAS', 'I-95 corridor'],
    automated: true
  },
  {
    id: 'saas-pa-aston',
    name: '146 Conchester',
    commonName: 'Conchester',
    address: '146 Conchester Hwy',
    city: 'Aston Township',
    state: 'PA',
    zip: '19014',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '201-323-6323',
    yardLink: 'https://www.therigh ut.com/details/146-c onchester?duration=monthly',
    features: ['SAAS', 'Pennsylvania'],
    automated: true
  },
  {
    id: 'saas-md-churchville',
    name: '3035 Churchville Road',
    commonName: 'Truckspace - Churchville',
    address: '3035 Churchville Rd',
    city: 'Churchville',
    state: 'MD',
    zip: '21028',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '201-323-6323',
    yardLink: 'https://www.therigh ut.com/details/3035-churchville-road?duration=monthly',
    features: ['SAAS', 'Maryland'],
    automated: true
  },
  {
    id: 'saas-md-baltimore',
    name: '901 Kresson Street',
    commonName: 'Realize Truck Parking - Baltimore',
    address: '901 S Kresson St',
    city: 'Baltimore',
    state: 'MD',
    zip: '21224',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therigh.ut.com/details/901-kresson-street?duration=monthly',
    features: ['SAAS', 'Realize network', 'Baltimore'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-nj-bayonne',
    name: '148 E 5th St',
    commonName: 'Realize - Bayonne',
    address: '148 E 5th St',
    city: 'Bayonne',
    state: 'NJ',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/150-e-5th-st?duration=monthly',
    features: ['SAAS', 'Realize network', 'New Jersey'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-pa-westmifflin',
    name: '2930 Lebanon Church',
    commonName: 'Church Road - West Mifflin',
    address: '2930 Lebanon Church Rd',
    city: 'West Mifflin',
    state: 'PA',
    zip: '15122',
    type: 'saas',
    category: 'east_coast',
    contactPhone: '201-323-6323',
    yardLink: 'https://www.therigh ut.com/details/2930-lebanon-church?duration=monthly',
    features: ['SAAS', 'Pittsburgh area'],
    automated: true
  },

  // ==================== SAAS YARDS - FLORIDA ====================
  {
    id: 'saas-fl-jacksonville-aviles',
    name: 'Aviles Robbins Truck Parking',
    commonName: 'Aviles Robbins - Jacksonville',
    address: '11950 Camden Rd',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32218',
    type: 'saas',
    category: 'florida',
    contactPhone: '904-434-4267',
    yardLink: 'https://www.therigh ut.com/details/aviles-robbins-truck-parking?duration=monthly',
    features: ['SAAS', 'Jacksonville'],
    automated: true
  },
  {
    id: 'saas-fl-jacksonville-troy',
    name: 'Troy\'s Big Truck Park',
    commonName: 'Troy\'s - Jacksonville',
    address: '6799 Pickett Dr',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32219',
    type: 'saas',
    category: 'florida',
    contactPhone: '904-219-5834',
    contactEmail: 'troytruckparking@gmail.com',
    yardLink: 'https://www.therigh ut.com/details/troys-big-truck-park?duration=monthly',
    features: ['SAAS', 'Jacksonville'],
    automated: true
  },
  {
    id: 'saas-fl-jacksonville-icparking',
    name: 'iCparking Jacksonville',
    commonName: 'iCparking - Jacksonville',
    address: '5387 Pickettville Rd',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32254',
    type: 'saas',
    category: 'florida',
    contactPhone: '866-337-7275',
    contactEmail: 'info@icparkingfl.com',
    yardLink: 'https://www.therigh ut.com/details/iCparking-jacksonville?duration=monthly',
    features: ['SAAS', 'Jacksonville'],
    automated: true
  },
  {
    id: 'saas-fl-jacksonville-edgewood',
    name: '4215 Edgewood Drive',
    commonName: 'Realize Truck Parking - Jacksonville',
    address: '4215 Edgewood Dr',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32254',
    type: 'saas',
    category: 'florida',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therigh ut.com/details/4215-e dgewood-drive?duration=monthly',
    features: ['SAAS', 'Realize network', 'Jacksonville'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-fl-groveland',
    name: 'St. Christopher\'s Big Rig Parking & Storage',
    commonName: 'St. Christopher\'s - Groveland',
    address: '20731 US-27',
    city: 'Groveland',
    state: 'FL',
    zip: '34736',
    type: 'saas',
    category: 'florida',
    contactPhone: '833-808-7275',
    yardLink: 'https://www.therigh ut.com/details/st-chri stophers-big-rig-par king-storage?duration=monthly',
    features: ['SAAS', 'Central Florida'],
    automated: true
  },
  {
    id: 'saas-fl-apopka',
    name: '2001 Rock Springs Rd',
    commonName: 'Orlando Industrial - Apopka',
    address: '2001 Rock Springs Rd',
    city: 'Apopka',
    state: 'FL',
    zip: '32712',
    type: 'saas',
    category: 'florida',
    contactPhone: '407-756-6869',
    yardLink: 'https://www.therigh ut.com/details/2001-r ock-springs-rd?duration=monthly',
    features: ['SAAS', 'Orlando area'],
    automated: true
  },
  {
    id: 'saas-fl-orlando-orange',
    name: '10838 S Orange Ave.',
    commonName: 'Advance Group USA - Orange',
    address: '10838 S Orange Ave',
    city: 'Orlando',
    state: 'FL',
    zip: '32824',
    type: 'saas',
    category: 'florida',
    contactPhone: '407-720-5885',
    yardLink: 'https://www.therigh ut.com/details/10838-s-orange-ave?duration=monthly',
    features: ['SAAS', 'Orlando'],
    automated: true
  },
  {
    id: 'saas-fl-orlando-thorpe',
    name: '400 Thorpe',
    commonName: 'Advance Group USA - Thorpe',
    address: '400 Thorpe Rd',
    city: 'Orlando',
    state: 'FL',
    zip: '32824',
    type: 'saas',
    category: 'florida',
    contactPhone: '407-720-5885',
    contactEmail: 'reservations@advancegroupusa.com',
    yardLink: 'https://www.therighut.com/details/400-thorp e?duration=monthly',
    features: ['SAAS', 'Orlando'],
    notes: 'Note: Customers pronounce "Thorpe" in different ways',
    automated: true
  },
  {
    id: 'saas-fl-orlando-boggy',
    name: 'HEAVY TRUCK PITS',
    commonName: 'Jaily Storage - Orlando',
    address: '10301 Boggy Creek Rd',
    city: 'Orlando',
    state: 'FL',
    zip: '32824',
    type: 'saas',
    category: 'florida',
    contactPhone: '813-363-1828',
    yardLink: 'https://www.therighut.com/details/heavy-truck-pits?duration=monthly',
    features: ['SAAS', 'Orlando area'],
    automated: true
  },
  {
    id: 'saas-fl-mulberry',
    name: 'CEM Enterprise Inc',
    commonName: 'CEM Enterprise Inc',
    address: '4100 State Rd 60',
    city: 'Mulberry',
    state: 'FL',
    zip: '33860',
    type: 'saas',
    category: 'florida',
    contactPhone: '813-708-7273',
    yardLink: 'https://www.therighut.com/details/cem-enterprise-inc?duration=monthly',
    features: ['SAAS', 'Central Florida'],
    automated: true
  },
  {
    id: 'saas-fl-bradenton',
    name: '303 301 Blvd W',
    commonName: 'Realize Truck Parking - Bradenton',
    address: '303 301 Blvd W',
    city: 'Bradenton',
    state: 'FL',
    zip: '34205',
    type: 'saas',
    category: 'florida',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/303-301-bvd-w?duration=monthly',
    features: ['SAAS', 'Realize network', 'Bradenton'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-fl-avonpark-wehaul',
    name: 'We-Haul Logistics',
    commonName: 'Avon Park Yard',
    address: '707 W Oak Ln St',
    city: 'Avon Park',
    state: 'FL',
    zip: '33825',
    type: 'saas',
    category: 'florida',
    contactPhone: '786-379-1980',
    yardLink: 'https://www.therighut.com/details/we-haul-logistics?duration=monthly',
    features: ['SAAS', 'Central Florida'],
    automated: true
  },
  {
    id: 'saas-fl-sebring-avonpark',
    name: 'Avon Park Yard',
    commonName: 'Avon Park Yard - Sebring',
    address: '7406 U.S. Hwy 27 S',
    city: 'Sebring',
    state: 'FL',
    zip: '33876',
    type: 'saas',
    category: 'florida',
    contactPhone: '863-600-3626',
    yardLink: 'https://www.therighut.com/details/avonpark-yard?duration=monthly',
    features: ['SAAS', 'Central Florida'],
    automated: true
  },
  {
    id: 'saas-fl-sebring-route66',
    name: '600 State Route 66',
    commonName: '600 State Route 66 - Sebring',
    address: '600 State Rte 66',
    city: 'Sebring',
    state: 'FL',
    zip: '33875',
    type: 'saas',
    category: 'florida',
    contactPhone: '863-600-3626',
    yardLink: 'https://www.therigh ut.com/details/600-s tate-route-667durati-on-monthly',
    features: ['SAAS', 'Sebring'],
    automated: true
  },
  {
    id: 'saas-fl-englewood',
    name: 'Park Store Go Englewood',
    commonName: 'Park Store Go - Englewood',
    address: '101 Paul Morris Dr',
    city: 'Englewood',
    state: 'FL',
    zip: '34223',
    type: 'saas',
    category: 'florida',
    contactPhone: '941-730-7723',
    yardLink: 'https://www.therigh ut.com/details/park-s tore-go-englewood?duration=monthly',
    features: ['SAAS', 'Southwest Florida'],
    automated: true
  },
  {
    id: 'saas-fl-pompanobeach-powerline',
    name: '4250 N Powerline Rd Pompano Beach',
    commonName: 'Realize Truck Parking - Pompano',
    address: '4250 N Powerline Rd',
    city: 'Pompano Beach',
    state: 'FL',
    zip: '33073',
    type: 'saas',
    category: 'florida',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therigh ut.com/details/4250-n-powerline-rd-pom-pano-beach?duration=monthly',
    features: ['SAAS', 'Realize network', 'Pompano Beach'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-fl-pompanobeach-12th',
    name: '1001 NW 12TH AVE Pompano',
    commonName: '1001 NW 12TH AVE Pompano',
    address: '1001 NW 12th Terrace',
    city: 'Pompano Beach',
    state: 'FL',
    zip: '33069',
    type: 'saas',
    category: 'florida',
    contactPhone: '570-760-9031',
    yardLink: 'https://www.therigh ut.com/details/1001-n w-12th-ave-pompan-o?duration=monthly',
    features: ['SAAS', 'Pompano Beach'],
    automated: true
  },
  {
    id: 'saas-fl-davie-staterd84',
    name: '10450 West State Road 84, Davie, FL',
    commonName: '10450 W State Rd 84 - Davie',
    address: '10450 W State Rd 84',
    city: 'Davie',
    state: 'FL',
    zip: '33324',
    type: 'saas',
    category: 'florida',
    contactPhone: '570-760-9031',
    yardLink: 'https://www.therigh ut.com/details/10450 -west-state-road-84-davie-fi?duration=monthly',
    features: ['SAAS', 'Davie'],
    automated: true
  },
  {
    id: 'saas-fl-hialeah',
    name: '13890 NW 186th Street',
    commonName: 'Realize Truck Parking - Hialeah',
    address: '13890 NW 186th St',
    city: 'Hialeah',
    state: 'FL',
    zip: '33018',
    type: 'saas',
    category: 'florida',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therigh ut.com/details/13890 -nw-186th-street?duration=monthly',
    features: ['SAAS', 'Realize network', 'Miami area'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-fl-westpalmbeach',
    name: 'West Palm Beach',
    commonName: 'Realize Truck Parking - West Palm Beach',
    address: '829 Benoist Farms Rd',
    city: 'West Palm Beach',
    state: 'FL',
    zip: '33411',
    type: 'saas',
    category: 'florida',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therigh ut.com/details/west-palm-beach?duration=monthly',
    features: ['SAAS', 'Realize network', 'West Palm Beach'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-fl-davie-595',
    name: '595 Truck Stop',
    commonName: 'Florida 595 Truck Stop',
    address: '2705 Burris Road',
    city: 'Davie',
    state: 'FL',
    type: 'saas',
    category: 'florida',
    contactPhone: '954-357-1480',
    contactEmail: 'reservations@595truckstop.com',
    yardLink: 'https://www.therigh ut.com/details/595-truck-stop?duration=monthly',
    features: ['SAAS', 'Truck stop', 'Gate access'],
    accessInstructions: 'Gate - CONFIRM AVAILABILITY AT THE GATE. PROVIDE YOUR BOOKING CONFIRMATION TO THE GATE ATTENDANT',
    automated: true
  },
  {
    id: 'saas-fl-jacksonville-performance',
    name: 'Performance Truck Parking JAX',
    commonName: 'Performance Truck Parking JAX',
    address: '698 Imeson Park Blvd',
    city: 'Jacksonville',
    state: 'FL',
    zip: '32218',
    type: 'saas',
    category: 'florida',
    contactPhone: '757-876-9310',
    contactEmail: 'performancetruckparkingjax@gmail.com',
    yardLink: 'https://www.therigh ut.com/details/performance-truck-parking-jax?duration=monthly',
    features: ['SAAS', 'Gate access', 'Jacksonville'],
    accessInstructions: 'Gate - code',
    automated: true
  },

  // ==================== SAAS YARDS - NATIONAL/OTHER ====================
  {
    id: 'saas-nv-lasvegas-adams',
    name: '11545 North Donald Lee Adams Way',
    commonName: 'Realize Truck Parking - North Vegas',
    address: '11545 North Vegas Logistics Center Building 2, N. Donald Lee Adams Way',
    city: 'North Las Vegas',
    state: 'NV',
    zip: '89165',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/11545-north-donald-lee-adams-way?duration=monthly',
    features: ['SAAS', 'Realize network', 'Las Vegas'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-nv-lasvegas-decatur',
    name: '13850 S Decatur Boulevard',
    commonName: 'Realize Truck Parking - Las Vegas',
    address: '13850 South Decatur Boulevard',
    city: 'Las Vegas',
    state: 'NV',
    zip: '89141',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '888-641-7275',
    contactEmail: 'max@werealize.io',
    yardLink: 'https://www.therighut.com/details/13850-s-decatur-boulevard?duration=monthly',
    features: ['SAAS', 'Realize network', 'Las Vegas'],
    notes: 'Request refund via email: max@werealize.io',
    automated: true
  },
  {
    id: 'saas-az-glendale',
    name: 'M G TRUCK PARKING',
    commonName: 'MG - Phoenix',
    address: '7190 North 110th Avenue',
    city: 'Glendale',
    state: 'AZ',
    zip: '85307',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '623-932-3800',
    contactEmail: 'ksimpson@mangatgroup.com',
    yardLink: 'https://www.therighut.com/details/in-g-truck-parking?duration=monthly',
    features: ['SAAS', 'Phoenix area'],
    automated: true
  },
  {
    id: 'saas-az-phoenix',
    name: 'Rush Truck Park',
    commonName: 'Rush - Phoenix',
    address: '3201 West Broadway Road',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85041',
    type: 'saas',
    category: 'west_coast',
    contactPhone: '602-243-5400',
    contactEmail: 'info@rushtruckpark.com',
    yardLink: 'https://www.therighut.com/details/rush-truck-park?duration=monthly',
    features: ['SAAS', 'Phoenix'],
    automated: true
  },
  {
    id: 'saas-ar-littlerock',
    name: 'Little Rock Truck Parking',
    commonName: '5 Production Dr - Little Rock',
    address: '5 Production Dr',
    city: 'Little Rock',
    state: 'AR',
    type: 'saas',
    category: 'southeast',
    contactPhone: '516-965-2050',
    contactEmail: 'ian@halliganindustrial.com',
    features: ['SAAS', 'Little Rock'],
    notes: 'No link available',
    automated: true
  },
  {
    id: 'saas-al-foley',
    name: 'BALDWIN INDUSTRIAL STORAGE AND WAREHOUSING',
    commonName: 'Baldwin - Foley',
    address: 'Lot 3Bl, Foley Beach Expressway Industrial Park',
    city: 'Foley',
    state: 'AL',
    type: 'saas',
    category: 'southeast',
    contactPhone: '251-243-2064',
    contactEmail: 'info@baldwintruckparking.com',
    yardLink: 'https://www.therigh ut.com/details/baldwin-industrial-storage-and-warehousing?duration=monthly',
    features: ['SAAS', 'Smart Gate', 'Alabama'],
    accessInstructions: 'Smart Gate',
    automated: true
  },
  {
    id: 'saas-mo-bridgeton-dropyard',
    name: 'Drop Yard Storage STL',
    commonName: 'Drop Yard - Bridgeton',
    address: '13816 Missouri Bottom Road',
    city: 'Bridgeton',
    state: 'MO',
    zip: '63044',
    type: 'saas',
    category: 'midwest',
    contactPhone: '561-556-8607',
    contactEmail: 'kolten@dropyardstorage.com',
    yardLink: 'https://www.therigh ut.com/details/drop-yard-storage-stl?duration=monthly',
    features: ['SAAS', 'Gate access', 'St. Louis'],
    accessInstructions: 'Gate - Convenient access points',
    automated: true
  },
];

// Helper functions
export const getYardCountByType = (type: YardType): number => {
  return YARDS.filter(yard => yard.type === type).length;
};

export const getYardCountByCategory = (category: YardCategory): number => {
  return YARDS.filter(yard => yard.category === category).length;
};

export const getUniqueStates = (): string[] => {
  const states = YARDS.map(yard => yard.state);
  return Array.from(new Set(states)).sort();
};

export const getUniqueCities = (): string[] => {
  const cities = YARDS.map(yard => `${yard.city}, ${yard.state}`);
  return Array.from(new Set(cities)).sort();
};

// Categorías para filtros UI
export const YARD_CATEGORIES = [
  { id: 'all', label: 'All Yards', count: YARDS.length, type: 'all' as const },
  { id: 'full_service', label: 'Full Service Yards', count: getYardCountByType('full_service'), type: 'full_service' as const },
  { id: 'saas', label: 'SAAS Yards', count: getYardCountByType('saas'), type: 'saas' as const },
  { id: 'west_coast', label: 'West Coast', count: getYardCountByCategory('west_coast'), type: 'saas' as const },
  { id: 'texas', label: 'Texas', count: getYardCountByCategory('texas'), type: 'saas' as const },
  { id: 'midwest', label: 'Midwest', count: getYardCountByCategory('midwest'), type: 'saas' as const },
  { id: 'southeast', label: 'Southeast', count: getYardCountByCategory('southeast'), type: 'saas' as const },
  { id: 'east_coast', label: 'East Coast', count: getYardCountByCategory('east_coast'), type: 'saas' as const },
  { id: 'florida', label: 'Florida', count: getYardCountByCategory('florida'), type: 'saas' as const },
];

// Función para buscar yardas
export const searchYards = (query: string, category?: string): Yard[] => {
  const lowerQuery = query.toLowerCase();
  
  return YARDS.filter(yard => {
    // Filtrar por categoría si se especifica
    if (category && category !== 'all' && yard.category !== category && yard.type !== category) {
      return false;
    }
    
    // Buscar en múltiples campos
    return (
      yard.name.toLowerCase().includes(lowerQuery) ||
      yard.commonName.toLowerCase().includes(lowerQuery) ||
      yard.city.toLowerCase().includes(lowerQuery) ||
      yard.state.toLowerCase().includes(lowerQuery) ||
      yard.address.toLowerCase().includes(lowerQuery) ||
      (yard.contactPhone && yard.contactPhone.includes(query)) ||
      (yard.contactEmail && yard.contactEmail.toLowerCase().includes(lowerQuery))
    );
  });
};